version: "3.9"
   
services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/code/staticfiles
    volumes_from:
      - web
    depends_on:
      - web

  db:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env-docker

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: ./
    command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn django_celery.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/code
      - ./staticfiles:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env-docker
    depends_on:
      - redis
      - db
      - celery
      - celery-beat

  celery:
    build: ./
    command: celery -A django_celery worker -l info
    volumes:
      - ./:/code
    env_file:
      - ./.env-docker
    depends_on:
      - redis
      - db

  celery-beat:
    build: ./
    command: celery -A django_celery beat -l info
    volumes:
      - ./:/code
    env_file:
      - ./.env-docker
    depends_on:
      - redis
      - db
