# Generated by Django 3.1.7 on 2021-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('url', models.URLField(help_text='The URL to the news', max_length=255, verbose_name='News URL')),
                ('image_url', models.URLField(help_text='The URL to the news image', max_length=255, verbose_name='Image URL')),
                ('published_at', models.DateTimeField(verbose_name='Created on')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-published_at', 'title'],
            },
        ),
    ]
